" Name:         WWDC16
" Description:  Colorful dark color scheme for Vim inspired by Apple's WWDC16 page
" Author:       Lifepillar <lifepillar@lifepillar.me>
" URL:          https://github.com/lifepillar/vim-wwdc16-theme
" License:      MIT
" Last Change:  2025 May 26

" Generated by Colortemplate v3.0.0-beta1

set background=dark

hi clear
let g:colors_name = 'wwdc16'

let g:terminal_ansi_colors = ['#292c36', '#e64547', '#42a647', '#c98351', '#4670d8', '#d24e9b', '#64878f', '#949494', '#353547', '#f84547', '#95c76f', '#efa16b', '#5283ff', '#8485ce', '#00aba5', '#ffffff']

let s:transp_bg = get(g:, 'wwdc16_transp_bg', 0)
let s:italic = has('gui_running') || has('nvim') || (&t_ZH != '' && &t_ZH != '[7m' && !has('win32'))

hi! link Conditional Statement
hi! link CurSearch Search
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Define PreProc
hi! link Exception Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link MessageWindow WarningMsg
hi! link PmenuExtra Pmenu
hi! link PmenuExtraSel PmenuSel
hi! link PmenuKind Pmenu
hi! link PmenuKindSel PmenuSel
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link TabPanel TabLine
hi! link TabPanelFill TabLineFill
hi! link TabPanelSel TabLineSel
hi! link Tag Special
hi! link TermCursor Cursor
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor
hi Normal guifg=#ffffff guibg=#292c36 guisp=NONE gui=NONE ctermfg=231 ctermbg=236 cterm=NONE term=NONE
hi Added guifg=#42a647 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE term=bold
hi Boolean guifg=#95c76f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE term=NONE
hi Changed guifg=#c98351 guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE term=bold,italic
hi Character guifg=#c98351 guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE term=NONE
hi ColorColumn guifg=NONE guibg=#353547 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE term=reverse
hi CommandMode guifg=#d24e9b guibg=#ffffff guisp=NONE gui=reverse ctermfg=169 ctermbg=231 cterm=reverse term=reverse
hi Comment guifg=#949494 guibg=NONE guisp=NONE gui=italic ctermfg=246 ctermbg=NONE cterm=italic term=italic
hi Conceal guifg=#64878f guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE term=NONE
hi Constant guifg=#c98351 guibg=NONE guisp=NONE gui=NONE ctermfg=173 ctermbg=NONE cterm=NONE term=bold,italic
hi Cursor guifg=#ffffff guibg=#4670d8 guisp=NONE gui=NONE ctermfg=231 ctermbg=26 cterm=NONE term=NONE
hi CursorColumn guifg=NONE guibg=#353547 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE term=reverse
hi CursorIM guifg=NONE guibg=#ffffff guisp=NONE gui=NONE ctermfg=NONE ctermbg=231 cterm=NONE term=NONE
hi CursorLine guifg=NONE guibg=#353547 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE term=underline
hi CursorLineNr guifg=#ffffff guibg=#353547 guisp=NONE gui=NONE ctermfg=231 ctermbg=237 cterm=NONE term=bold,italic,reverse,underline
hi Debug guifg=#d24e9b guibg=NONE guisp=NONE gui=NONE ctermfg=169 ctermbg=NONE cterm=NONE term=NONE
hi Delimiter guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE term=NONE
hi DiffAdd guifg=#95c76f guibg=#292c36 guisp=NONE gui=reverse ctermfg=150 ctermbg=236 cterm=reverse term=reverse,underline
hi DiffChange guifg=#c98351 guibg=#ffffff guisp=NONE gui=reverse ctermfg=173 ctermbg=231 cterm=reverse term=reverse,underline
hi DiffDelete guifg=#e64547 guibg=#ffffff guisp=NONE gui=reverse ctermfg=167 ctermbg=231 cterm=reverse term=reverse,underline
hi DiffText guifg=#42a647 guibg=#ffffff guisp=NONE gui=bold,reverse ctermfg=71 ctermbg=231 cterm=bold,reverse term=bold,reverse,underline
hi Directory guifg=#95c76f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE term=NONE
hi EndOfBuffer guifg=#353547 guibg=NONE guisp=NONE gui=NONE ctermfg=237 ctermbg=NONE cterm=NONE term=NONE
hi Error guifg=#e64547 guibg=#ffffff guisp=NONE gui=reverse ctermfg=167 ctermbg=231 cterm=reverse term=reverse
hi ErrorMsg guifg=#e64547 guibg=#ffffff guisp=NONE gui=reverse ctermfg=167 ctermbg=231 cterm=reverse term=bold,italic,reverse
hi Float guifg=#95c76f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE term=NONE
hi FoldColumn guifg=#949494 guibg=#353547 guisp=NONE gui=NONE ctermfg=246 ctermbg=237 cterm=NONE term=reverse
hi Folded guifg=#949494 guibg=#353547 guisp=NONE gui=italic ctermfg=246 ctermbg=237 cterm=italic term=italic,reverse,underline
hi Function guifg=#42a647 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE term=NONE
hi Identifier guifg=#00aba5 guibg=NONE guisp=NONE gui=NONE ctermfg=37 ctermbg=NONE cterm=NONE term=italic
hi Ignore guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE term=NONE
hi IncSearch guifg=#d24e9b guibg=#ffffff guisp=NONE gui=standout ctermfg=169 ctermbg=231 cterm=reverse term=bold,italic,reverse
hi Include guifg=#e64547 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE term=NONE
hi InsertMode guifg=#95c76f guibg=#292c36 guisp=NONE gui=reverse ctermfg=150 ctermbg=236 cterm=reverse term=reverse
hi Keyword guifg=#64878f guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE term=NONE
hi Label guifg=#42a647 guibg=NONE guisp=NONE gui=NONE ctermfg=71 ctermbg=NONE cterm=NONE term=NONE
hi LineNr guifg=#949494 guibg=#353547 guisp=NONE gui=NONE ctermfg=246 ctermbg=237 cterm=NONE term=reverse
hi MatchParen guifg=#353547 guibg=#c98351 guisp=NONE gui=bold,reverse ctermfg=237 ctermbg=173 cterm=bold,reverse term=bold,underline
hi ModeMsg guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE term=NONE
hi MoreMsg guifg=#949494 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE term=NONE
hi NonText guifg=#ffffff guibg=NONE guisp=NONE gui=NONE ctermfg=231 ctermbg=NONE cterm=NONE term=NONE
hi NormalMode guifg=#949494 guibg=#ffffff guisp=NONE gui=reverse ctermfg=246 ctermbg=231 cterm=reverse term=reverse
hi Number guifg=#95c76f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE term=NONE
hi Operator guifg=#00aba5 guibg=NONE guisp=NONE gui=NONE ctermfg=37 ctermbg=NONE cterm=NONE term=NONE
hi Pmenu guifg=#292c36 guibg=#64878f guisp=NONE gui=NONE ctermfg=236 ctermbg=66 cterm=NONE term=reverse
hi PmenuSbar guifg=#353547 guibg=#353547 guisp=NONE gui=NONE ctermfg=237 ctermbg=237 cterm=NONE term=NONE
hi PmenuSel guifg=#ffffff guibg=#c98351 guisp=NONE gui=NONE ctermfg=231 ctermbg=173 cterm=NONE term=NONE
hi PmenuThumb guifg=#353547 guibg=#c98351 guisp=NONE gui=NONE ctermfg=237 ctermbg=173 cterm=NONE term=NONE
hi PreProc guifg=#d24e9b guibg=NONE guisp=NONE gui=NONE ctermfg=169 ctermbg=NONE cterm=NONE term=italic
hi Question guifg=#949494 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE term=standout
hi Removed guifg=#e64547 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE term=reverse,strikethrough
hi ReplaceMode guifg=#c98351 guibg=#292c36 guisp=NONE gui=reverse ctermfg=173 ctermbg=236 cterm=reverse term=reverse
hi Search guifg=#c98351 guibg=#ffffff guisp=NONE gui=reverse ctermfg=173 ctermbg=231 cterm=reverse term=italic,underline
hi SignColumn guifg=#949494 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE term=reverse
hi Special guifg=#d24e9b guibg=NONE guisp=NONE gui=NONE ctermfg=169 ctermbg=NONE cterm=NONE term=bold,italic
hi SpecialChar guifg=#d24e9b guibg=NONE guisp=NONE gui=NONE ctermfg=169 ctermbg=NONE cterm=NONE term=NONE
hi SpecialComment guifg=#e64547 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE term=NONE
hi SpecialKey guifg=#949494 guibg=NONE guisp=NONE gui=NONE ctermfg=246 ctermbg=NONE cterm=NONE term=bold
hi SpellBad guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl ctermfg=104 ctermbg=NONE cterm=underline term=italic,underline
hi SpellCap guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl ctermfg=104 ctermbg=NONE cterm=underline term=italic,underline
hi SpellLocal guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl ctermfg=104 ctermbg=NONE cterm=underline term=italic,underline
hi SpellRare guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl ctermfg=104 ctermbg=NONE cterm=underline term=italic,underline
hi Statement guifg=#64878f guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE term=bold
hi StatusLine guifg=#64878f guibg=#ffffff guisp=NONE gui=reverse ctermfg=66 ctermbg=231 cterm=reverse term=bold,reverse
hi StatusLineNC guifg=#64878f guibg=#292c36 guisp=NONE gui=reverse ctermfg=66 ctermbg=236 cterm=reverse term=reverse
hi StorageClass guifg=#00aba5 guibg=NONE guisp=NONE gui=NONE ctermfg=37 ctermbg=NONE cterm=NONE term=NONE
hi String guifg=#95c76f guibg=NONE guisp=NONE gui=NONE ctermfg=150 ctermbg=NONE cterm=NONE term=NONE
hi Structure guifg=#e64547 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE term=NONE
hi TabLine guifg=#292c36 guibg=#64878f guisp=NONE gui=NONE ctermfg=236 ctermbg=66 cterm=NONE term=italic,reverse,underline
hi TabLineFill guifg=#ffffff guibg=#64878f guisp=NONE gui=NONE ctermfg=231 ctermbg=66 cterm=NONE term=reverse,underline
hi TabLineSel guifg=#ffffff guibg=#64878f guisp=NONE gui=NONE ctermfg=231 ctermbg=66 cterm=NONE term=bold
hi TermCursorNC guifg=#ffffff guibg=#949494 guisp=NONE gui=NONE ctermfg=231 ctermbg=246 cterm=NONE term=NONE
hi Terminal guifg=#ffffff guibg=#292c36 guisp=NONE gui=NONE ctermfg=231 ctermbg=236 cterm=NONE term=NONE
hi Title guifg=#c98351 guibg=NONE guisp=NONE gui=bold ctermfg=173 ctermbg=NONE cterm=bold term=bold
hi Todo guifg=#d24e9b guibg=NONE guisp=NONE gui=bold ctermfg=169 ctermbg=NONE cterm=bold term=bold,underline
hi ToolbarButton guifg=#64878f guibg=#353547 guisp=NONE gui=bold ctermfg=66 ctermbg=237 cterm=bold term=bold,reverse
hi ToolbarLine guifg=NONE guibg=#353547 guisp=NONE gui=NONE ctermfg=NONE ctermbg=237 cterm=NONE term=reverse
hi Type guifg=#8485ce guibg=NONE guisp=NONE gui=NONE ctermfg=104 ctermbg=NONE cterm=NONE term=bold
hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline term=underline
hi VertSplit guifg=#353547 guibg=#64878f guisp=NONE gui=NONE ctermfg=237 ctermbg=66 cterm=NONE term=reverse
hi Visual guifg=#4670d8 guibg=#ffffff guisp=NONE gui=reverse ctermfg=26 ctermbg=231 cterm=reverse term=reverse
hi VisualMode guifg=#4670d8 guibg=#ffffff guisp=NONE gui=reverse ctermfg=26 ctermbg=231 cterm=reverse term=reverse
hi VisualNOS guifg=#ffffff guibg=#4670d8 guisp=NONE gui=NONE ctermfg=231 ctermbg=26 cterm=NONE term=NONE
hi WarningMsg guifg=#e64547 guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE term=standout
hi WildMenu guifg=#ffffff guibg=#d24e9b guisp=NONE gui=NONE ctermfg=231 ctermbg=169 cterm=NONE term=bold

if str2nr(&t_Co) >= 256
  if s:italic == 0
    hi Comment cterm=NONE
    hi Folded cterm=NONE
  endif
  if s:transp_bg == 1
    hi Normal ctermbg=NONE
    hi CursorLineNr ctermbg=NONE
    hi FoldColumn ctermbg=NONE
    hi LineNr ctermbg=NONE
    hi Terminal ctermbg=NONE
  endif
  unlet s:italic
  unlet s:transp_bg
  finish
endif

if str2nr(&t_Co) >= 8
  hi IncSearch ctermfg=DarkMagenta ctermbg=White cterm=reverse
  hi SpellBad cterm=underline
  hi SpellCap cterm=underline
  hi SpellLocal cterm=underline
  hi SpellRare cterm=underline
  if s:italic == 0
    hi Comment cterm=NONE
    hi Folded cterm=NONE
  endif
  if s:transp_bg == 1
    hi Normal ctermbg=NONE
    hi CursorLineNr ctermbg=NONE
    hi FoldColumn ctermbg=NONE
    hi LineNr ctermbg=NONE
    hi Terminal ctermbg=NONE
  endif
  unlet s:italic
  unlet s:transp_bg
  finish
endif

" vim: et ts=8 sw=2 sts=2
