" Name:         WWDC16
" Description:  Colorful dark color scheme for Vim inspired by Apple's WWDC16 page
" Author:       Lifepillar <lifepillar@lifepillar.me>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-wwdc16-theme
" License:      This file is placed in the public domain
" Last Updated: Sat Jun 29 14:31:25 2019

" Generated by Colortemplate v2.0.0b3

set background=dark

hi clear
if exists('syntax_on')
  syntax reset
endif

let g:colors_name = 'wwdc16'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (((&t_ZH != '' && &t_ZH != '[7m') || has('gui_running')) && !has('iOS')) || has('nvim')

hi! link Repeat Statement
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Conditional Statement
hi! link Define PreProc
hi! link Exception Statement
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#292c36', '#e64547', '#42a647', '#c98351',
        \ '#4670d8', '#d24e9b', '#64878f', '#949494', '#353547', '#f84547',
        \ '#95c76f', '#efa16b', '#5283ff', '#8485ce', '#00aba5', '#ffffff']
  if has('nvim')
    let g:terminal_color_0 = '#292c36'
    let g:terminal_color_1 = '#e64547'
    let g:terminal_color_2 = '#42a647'
    let g:terminal_color_3 = '#c98351'
    let g:terminal_color_4 = '#4670d8'
    let g:terminal_color_5 = '#d24e9b'
    let g:terminal_color_6 = '#64878f'
    let g:terminal_color_7 = '#949494'
    let g:terminal_color_8 = '#353547'
    let g:terminal_color_9 = '#f84547'
    let g:terminal_color_10 = '#95c76f'
    let g:terminal_color_11 = '#efa16b'
    let g:terminal_color_12 = '#5283ff'
    let g:terminal_color_13 = '#8485ce'
    let g:terminal_color_14 = '#00aba5'
    let g:terminal_color_15 = '#ffffff'
  endif
  if get(g:, 'wwdc16_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#949494 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#949494 guibg=NONE guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  else
    hi Normal guifg=#ffffff guibg=#292c36 guisp=NONE gui=NONE cterm=NONE
    hi CursorLineNr guifg=#ffffff guibg=#353547 guisp=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#949494 guibg=#353547 guisp=NONE gui=NONE cterm=NONE
    hi LineNr guifg=#949494 guibg=#353547 guisp=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#ffffff guibg=#292c36 guisp=NONE gui=NONE cterm=NONE
  endif
  hi ColorColumn guifg=NONE guibg=#353547 guisp=NONE gui=NONE cterm=NONE
  hi Conceal guifg=#64878f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Cursor guifg=#ffffff guibg=#4670d8 guisp=NONE gui=NONE cterm=NONE
  hi CursorColumn guifg=NONE guibg=#353547 guisp=NONE gui=NONE cterm=NONE
  hi CursorLine guifg=NONE guibg=#353547 guisp=NONE gui=NONE cterm=NONE
  hi DiffAdd guifg=#95c76f guibg=#292c36 guisp=NONE gui=reverse cterm=reverse
  hi DiffChange guifg=#c98351 guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  hi DiffDelete guifg=#e64547 guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  hi DiffText guifg=#42a647 guibg=#ffffff guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#95c76f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#353547 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#e64547 guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  hi Folded guifg=#949494 guibg=#353547 guisp=NONE gui=italic cterm=italic
  hi IncSearch guifg=#d24e9b guibg=#ffffff guisp=NONE gui=standout cterm=standout
  hi MatchParen guifg=#353547 guibg=#c98351 guisp=NONE gui=bold,reverse cterm=bold,reverse
  hi ModeMsg guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#949494 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi NonText guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#292c36 guibg=#64878f guisp=NONE gui=NONE cterm=NONE
  hi PmenuSbar guifg=#353547 guibg=#353547 guisp=NONE gui=NONE cterm=NONE
  hi PmenuSel guifg=#ffffff guibg=#c98351 guisp=NONE gui=NONE cterm=NONE
  hi PmenuThumb guifg=#353547 guibg=#c98351 guisp=NONE gui=NONE cterm=NONE
  hi Question guifg=#949494 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Search guifg=#c98351 guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  hi SignColumn guifg=#949494 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#949494 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl cterm=undercurl
  hi SpellCap guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl cterm=undercurl
  hi SpellLocal guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl cterm=undercurl
  hi SpellRare guifg=#8485ce guibg=NONE guisp=#d24e9b gui=undercurl cterm=undercurl
  hi StatusLine guifg=#64878f guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  hi StatusLineNC guifg=#64878f guibg=#292c36 guisp=NONE gui=reverse cterm=reverse
  hi TabLine guifg=#292c36 guibg=#64878f guisp=NONE gui=NONE cterm=NONE
  hi TabLineFill guifg=#ffffff guibg=#64878f guisp=NONE gui=NONE cterm=NONE
  hi TabLineSel guifg=#ffffff guibg=#64878f guisp=NONE gui=NONE cterm=NONE
  hi Title guifg=#c98351 guibg=NONE guisp=NONE gui=bold cterm=bold
  hi VertSplit guifg=#353547 guibg=#64878f guisp=NONE gui=NONE cterm=NONE
  hi Visual guifg=#4670d8 guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  hi VisualNOS guifg=#ffffff guibg=#4670d8 guisp=NONE gui=NONE cterm=NONE
  hi WarningMsg guifg=#e64547 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi WildMenu guifg=#ffffff guibg=#d24e9b guisp=NONE gui=NONE cterm=NONE
  hi Boolean guifg=#95c76f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Character guifg=#c98351 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Comment guifg=#949494 guibg=NONE guisp=NONE gui=italic cterm=italic
  hi Constant guifg=#c98351 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Debug guifg=#d24e9b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Error guifg=#e64547 guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  hi Float guifg=#95c76f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Function guifg=#42a647 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#00aba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#ffffff guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Include guifg=#e64547 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#64878f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Label guifg=#42a647 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Number guifg=#95c76f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Operator guifg=#00aba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#d24e9b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Special guifg=#d24e9b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#d24e9b guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#e64547 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Statement guifg=#64878f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#00aba5 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi String guifg=#95c76f guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Structure guifg=#e64547 guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Todo guifg=#d24e9b guibg=NONE guisp=NONE gui=bold cterm=bold
  hi Type guifg=#8485ce guibg=NONE guisp=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=#ffffff guisp=NONE gui=NONE cterm=NONE
  hi ToolbarLine guifg=NONE guibg=#353547 guisp=NONE gui=NONE cterm=NONE
  hi ToolbarButton guifg=#64878f guibg=#353547 guisp=NONE gui=bold cterm=bold
  hi NormalMode guifg=#949494 guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  hi InsertMode guifg=#95c76f guibg=#292c36 guisp=NONE gui=reverse cterm=reverse
  hi ReplaceMode guifg=#c98351 guibg=#292c36 guisp=NONE gui=reverse cterm=reverse
  hi VisualMode guifg=#4670d8 guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  hi CommandMode guifg=#d24e9b guibg=#ffffff guisp=NONE gui=reverse cterm=reverse
  if !s:italics
    hi Folded gui=NONE cterm=NONE
    hi Comment gui=NONE cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC guifg=#ffffff guibg=#949494 guisp=NONE gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'wwdc16_transp_bg', 0)
    hi Normal ctermfg=231 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=231 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=246 ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=246 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=231 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=231 ctermbg=236 cterm=NONE
    if !has('patch-8.0.0616') && !has('nvim') " Fix for Vim bug
      set background=dark
    endif
    hi CursorLineNr ctermfg=231 ctermbg=237 cterm=NONE
    hi FoldColumn ctermfg=246 ctermbg=237 cterm=NONE
    hi LineNr ctermfg=246 ctermbg=237 cterm=NONE
    hi Terminal ctermfg=231 ctermbg=236 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi Conceal ctermfg=66 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=231 ctermbg=26 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffAdd ctermfg=150 ctermbg=236 cterm=reverse
  hi DiffChange ctermfg=173 ctermbg=231 cterm=reverse
  hi DiffDelete ctermfg=167 ctermbg=231 cterm=reverse
  hi DiffText ctermfg=71 ctermbg=231 cterm=bold,reverse
  hi Directory ctermfg=150 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=237 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=231 cterm=reverse
  hi Folded ctermfg=246 ctermbg=237 cterm=italic
  hi IncSearch ctermfg=169 ctermbg=231 cterm=reverse
  hi MatchParen ctermfg=237 ctermbg=173 cterm=bold,reverse
  hi ModeMsg ctermfg=231 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=246 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=231 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=236 ctermbg=66 cterm=NONE
  hi PmenuSbar ctermfg=237 ctermbg=237 cterm=NONE
  hi PmenuSel ctermfg=231 ctermbg=173 cterm=NONE
  hi PmenuThumb ctermfg=237 ctermbg=173 cterm=NONE
  hi Question ctermfg=246 ctermbg=NONE cterm=NONE
  hi Search ctermfg=173 ctermbg=231 cterm=reverse
  hi SignColumn ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=104 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=104 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=104 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=104 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=66 ctermbg=231 cterm=reverse
  hi StatusLineNC ctermfg=66 ctermbg=236 cterm=reverse
  hi TabLine ctermfg=236 ctermbg=66 cterm=NONE
  hi TabLineFill ctermfg=231 ctermbg=66 cterm=NONE
  hi TabLineSel ctermfg=231 ctermbg=66 cterm=NONE
  hi Title ctermfg=173 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=237 ctermbg=66 cterm=NONE
  hi Visual ctermfg=26 ctermbg=231 cterm=reverse
  hi VisualNOS ctermfg=231 ctermbg=26 cterm=NONE
  hi WarningMsg ctermfg=167 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=231 ctermbg=169 cterm=NONE
  hi Boolean ctermfg=150 ctermbg=NONE cterm=NONE
  hi Character ctermfg=173 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=246 ctermbg=NONE cterm=italic
  hi Constant ctermfg=173 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=169 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=231 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=231 cterm=reverse
  hi Float ctermfg=150 ctermbg=NONE cterm=NONE
  hi Function ctermfg=71 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=37 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=231 ctermbg=NONE cterm=NONE
  hi Include ctermfg=167 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=66 ctermbg=NONE cterm=NONE
  hi Label ctermfg=71 ctermbg=NONE cterm=NONE
  hi Number ctermfg=150 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=37 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=169 ctermbg=NONE cterm=NONE
  hi Special ctermfg=169 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=169 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=167 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=66 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=37 ctermbg=NONE cterm=NONE
  hi String ctermfg=150 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=167 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=169 ctermbg=NONE cterm=bold
  hi Type ctermfg=104 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=231 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi ToolbarButton ctermfg=66 ctermbg=237 cterm=bold
  hi NormalMode ctermfg=246 ctermbg=231 cterm=reverse
  hi InsertMode ctermfg=150 ctermbg=236 cterm=reverse
  hi ReplaceMode ctermfg=173 ctermbg=236 cterm=reverse
  hi VisualMode ctermfg=26 ctermbg=231 cterm=reverse
  hi CommandMode ctermfg=169 ctermbg=231 cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=231 ctermbg=246 cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'wwdc16_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=Gray ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=DarkGray cterm=NONE
    hi FoldColumn ctermfg=Gray ctermbg=DarkGray cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=DarkGray cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi Conceal ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi DiffAdd ctermfg=Green ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=DarkYellow ctermbg=White cterm=reverse
  hi DiffDelete ctermfg=DarkRed ctermbg=White cterm=reverse
  hi DiffText ctermfg=DarkGreen ctermbg=White cterm=bold,reverse
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=White cterm=reverse
  hi Folded ctermfg=Gray ctermbg=DarkGray cterm=italic
  hi IncSearch ctermfg=DarkMagenta ctermbg=White cterm=reverse
  hi MatchParen ctermfg=DarkGray ctermbg=DarkYellow cterm=bold,reverse
  hi ModeMsg ctermfg=White ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Gray ctermbg=NONE cterm=NONE
  hi NonText ctermfg=White ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi PmenuSbar ctermfg=DarkGray ctermbg=DarkGray cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=DarkYellow cterm=NONE
  hi PmenuThumb ctermfg=DarkGray ctermbg=DarkYellow cterm=NONE
  hi Question ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Search ctermfg=DarkYellow ctermbg=White cterm=reverse
  hi SignColumn ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Magenta ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=Magenta ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=Magenta ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=Magenta ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=DarkCyan ctermbg=White cterm=reverse
  hi StatusLineNC ctermfg=DarkCyan ctermbg=Black cterm=reverse
  hi TabLine ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=DarkCyan cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=DarkCyan cterm=NONE
  hi Title ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=DarkGray ctermbg=DarkCyan cterm=NONE
  hi Visual ctermfg=DarkBlue ctermbg=White cterm=reverse
  hi VisualNOS ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi WarningMsg ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Gray ctermbg=NONE cterm=italic
  hi Constant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Debug ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=White cterm=reverse
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Function ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi Include ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Number ctermfg=Green ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Structure ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkMagenta ctermbg=NONE cterm=bold
  hi Type ctermfg=Magenta ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi ToolbarButton ctermfg=DarkCyan ctermbg=DarkGray cterm=bold
  hi NormalMode ctermfg=Gray ctermbg=White cterm=reverse
  hi InsertMode ctermfg=Green ctermbg=Black cterm=reverse
  hi ReplaceMode ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi VisualMode ctermfg=DarkBlue ctermbg=White cterm=reverse
  hi CommandMode ctermfg=DarkMagenta ctermbg=White cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=White ctermbg=Gray cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Repeat            -> Statement
" QuickFixLine      -> Search
" StatusLineTerm    -> StatusLine
" StatusLineTermNC  -> StatusLineNC
" Conditional       -> Statement
" Define            -> PreProc
" Exception         -> Statement
" Macro             -> PreProc
" PreCondit         -> PreProc
" Tag               -> Special
" Typedef           -> Type
" lCursor           -> Cursor
" Background: dark
" Color: black                rgb( 41,  44,  54)   236        Black
" Color: red                  rgb(230,  69,  71)   167        DarkRed
" Color: green                rgb( 66, 166,  71)   71         DarkGreen
" Color: yellow               rgb(201, 131,  81)   173        DarkYellow
" Color: blue                 rgb( 70, 112, 216)   26         DarkBlue
" Color: magenta              rgb(210,  78, 155)   169        DarkMagenta
" Color: cyan                 rgb(100, 135, 143)   66         DarkCyan
" Color: white                rgb(148, 148, 148)   246        Gray
" Color: brightblack          rgb( 53,  53,  71)   237        DarkGray
" Color: brightred            rgb(248,  69,  71)   203        Red
" Color: brightgreen          rgb(149, 199, 111)   150        Green
" Color: brightyellow         rgb(239, 161, 107)   216        Yellow
" Color: brightblue           rgb( 82, 131, 255)   69         Blue
" Color: brightmagenta        rgb(132, 133, 206)   104        Magenta
" Color: brightcyan           rgb(  0, 171, 165)   37         Cyan
" Color: brightwhite          rgb(255, 255, 255)   231        White
" Term Colors: black red green yellow blue magenta cyan white
" Term Colors: brightblack brightred brightgreen brightyellow
" Term Colors: brightblue brightmagenta brightcyan brightwhite
" Variant: gui
" if get(g:, '@optionprefix_transp_bg', 0) && !has('gui_running')
" Variant: 256 8
" if get(g:, '@optionprefix_transp_bg', 0)
" Variant: gui 256 8
"     Normal           brightwhite       none
"     CursorLineNr     brightwhite       none
"     FoldColumn       white             none
"     LineNr           white             none
"     Terminal         brightwhite       none
" else
"     Normal           brightwhite       black
"     CursorLineNr     brightwhite       brightblack
"     FoldColumn       white             brightblack
"     LineNr           white             brightblack
"     Terminal         brightwhite       black
" endif
" ColorColumn          none              brightblack
" Conceal              cyan              none
" Cursor               brightwhite       blue
" CursorColumn         none              brightblack
" CursorLine           none              brightblack
" DiffAdd              brightgreen       black             reverse
" DiffChange           yellow            brightwhite       reverse
" DiffDelete           red               brightwhite       reverse
" DiffText             green             brightwhite       bold,reverse
" Directory            brightgreen       none
" EndOfBuffer          brightblack       none
" ErrorMsg             red               brightwhite       reverse
" Folded               white             brightblack       italic
" IncSearch            magenta           brightwhite       t=reverse g=standout
" MatchParen           brightblack       yellow            bold,reverse
" ModeMsg              brightwhite       none
" MoreMsg              white             none
" NonText              brightwhite       none
" Pmenu                black             cyan
" PmenuSbar            brightblack       brightblack
" PmenuSel             brightwhite       yellow
" PmenuThumb           brightblack       yellow
" Question             white             none
" Search               yellow            brightwhite       reverse
" SignColumn           white             none
" SpecialKey           white             none
" SpellBad             brightmagenta     none              s=magenta t=underline g=undercurl
" SpellCap             brightmagenta     none              s=magenta t=underline g=undercurl
" SpellLocal           brightmagenta     none              s=magenta t=underline g=undercurl
" SpellRare            brightmagenta     none              s=magenta t=underline g=undercurl
" StatusLine           cyan              brightwhite       reverse
" StatusLineNC         cyan              black             reverse
" TabLine              black             cyan
" TabLineFill          brightwhite       cyan
" TabLineSel           brightwhite       cyan
" Title                yellow            none              bold
" VertSplit            brightblack       cyan
" Visual               blue              brightwhite       reverse
" VisualNOS            brightwhite       blue
" WarningMsg           red               none
" WildMenu             brightwhite       magenta
" Boolean              brightgreen       none
" Character            yellow            none
" Comment              white             none              italic
" Constant             yellow            none
" Debug                magenta           none
" Delimiter            brightwhite       none
" Error                red               brightwhite       reverse
" Float                brightgreen       none
" Function             green             none
" Identifier           brightcyan        none
" Ignore               brightwhite       none
" Include              red               none
" Keyword              cyan              none
" Label                green             none
" Number               brightgreen       none
" Operator             brightcyan        none
" PreProc              magenta           none
" Special              magenta           none
" SpecialChar          magenta           none
" SpecialComment       red               none
" Statement            cyan              none
" StorageClass         brightcyan        none
" String               brightgreen       none
" Structure            red               none
" Todo                 magenta           none              bold
" Type                 brightmagenta     none
" Underlined           none              none              underline
" CursorIM             none              brightwhite
" ToolbarLine          none              brightblack
" ToolbarButton        cyan              brightblack       bold
" NormalMode           white             brightwhite       reverse
" InsertMode           brightgreen       black             reverse
" ReplaceMode          yellow            black             reverse
" VisualMode           blue              brightwhite       reverse
" CommandMode          magenta           brightwhite       reverse
" TermCursor        -> Cursor
" TermCursorNC         brightwhite       white
" Variant: 2
" Normal               omit   omit
" ColorColumn          omit   omit    reverse
" Conceal              omit   omit
" Cursor               omit   omit
" CursorColumn         omit   omit    reverse
" CursorLine           omit   omit    underline
" CursorLineNr         omit   omit    reverse,italic,bold,underline
" DiffAdd              omit   omit    reverse,underline
" DiffChange           omit   omit    reverse,underline
" DiffDelete           omit   omit    reverse,underline
" DiffText             omit   omit    bold,reverse,underline
" Directory            omit   omit
" EndOfBuffer          omit   omit
" ErrorMsg             omit   omit    bold,reverse,italic
" FoldColumn           omit   omit    reverse
" Folded               omit   omit    italic,reverse,underline
" IncSearch            omit   omit    reverse,bold,italic
" LineNr               omit   omit    reverse
" MatchParen           omit   omit    bold,underline
" ModeMsg              omit   omit
" MoreMsg              omit   omit
" NonText              omit   omit
" Pmenu                omit   omit    reverse
" PmenuSbar            omit   omit
" PmenuSel             omit   omit
" PmenuThumb           omit   omit
" Question             omit   omit    standout
" Search               omit   omit    underline,italic
" SignColumn           omit   omit    reverse
" SpecialKey           omit   omit    bold
" SpellBad             omit   omit    underline,italic
" SpellCap             omit   omit    underline,italic
" SpellLocal           omit   omit    underline,italic
" SpellRare            omit   omit    underline,italic
" StatusLine           omit   omit    reverse,bold
" StatusLineNC         omit   omit    reverse
" TabLine              omit   omit    reverse,underline,italic
" TabLineFill          omit   omit    reverse,underline
" TabLineSel           omit   omit    bold
" Title                omit   omit    bold
" VertSplit            omit   omit    reverse
" Visual               omit   omit    reverse
" VisualNOS            omit   omit
" WarningMsg           omit   omit    standout
" WildMenu             omit   omit    bold
" Comment              omit   omit    italic
" Constant             omit   omit    bold,italic
" Error                omit   omit    reverse
" Identifier           omit   omit    italic
" Ignore               omit   omit
" PreProc              omit   omit    italic
" Special              omit   omit    bold,italic
" Statement            omit   omit    bold
" Todo                 omit   omit    bold,underline
" Type                 omit   omit    bold
" Underlined           omit   omit    underline
" CursorIM             omit   omit
" ToolbarLine          omit   omit    reverse
" ToolbarButton        omit   omit    bold,reverse
